### ISSUE TITLE
Add WatWhenWhere

### ISSUE THREAD

**Issue by nwoodthorpe** [wattools/WatTools#1]
WatWhenWhere is a time management app for Waterloo students. Any way we could get it added to le list?

**Comment by kyl191** [comment]
Sure! Fork the repo, add your site to the respective JSON file in data (most likely general?) and send me a pull request.

**Comment by nwoodthorpe** [comment]
Done

**Comment by kyl191** [comment]
Merged & rebuilt. Looks fine
